version: "3.8"

services:
  db:
    container_name: hackson_db  # 変更された行
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./.env_mysql
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

volumes:
  mysql-data:
    name: mysql-volume2
